version: '3.9'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    # depends_on:
      # - db
    networks:
      - app-network

  frontend:
    build: ./chat
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  # db:
  #   image: mysql:latest
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: chatapp
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge